# Generated by Django 4.2.10 on 2024-03-27 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_commentrecipe_delete_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentrecipe",
            old_name="body",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="commentrecipe",
            name="approved",
        ),
        migrations.AlterField(
            model_name="commentrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
            ),
        ),
    ]
